functionsDirectory = "/home/drew/Code/GoLembrar/GoLembrar-server/dist/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/drew/Code/GoLembrar/GoLembrar-server/dist/src"
publishOrigin = "config"
command = "npm run build"
commandOrigin = "config"
functions = "/home/drew/Code/GoLembrar/GoLembrar-server/dist/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/main"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]