services:
  golembrar-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=golembrar
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./.docker/golembrar-db/data:/var/lib/golembrar-db/:delegated
    healthcheck:
      test:
        ['CMD-SHELL', "psql -h localhost -U test -d golembrar -c 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    depends_on:
      - golembrar-db

networks:
  default:
    driver: bridge
    name: golembrar

volumes:
  golembrar-db:
  rabbitmq_data:
