version: '3'
services:
  db:
    image: bitnami/postgresql
    ports:
      - 5431:5432
    environment:
      - POSTGRESQL_USERNAME=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=golembrar
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/:delegated