version: '3.8'
services:
  db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=golembrar
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/:delegated
    healthcheck:
      test: [ "CMD-SHELL", "psql -h localhost -U test -d golembrar -c 'SELECT 1;'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
  api:
    depends_on:
      db:
        condition: service_healthy
    build: .
    environment:
      - DATABASE_URL="postgresql://test:test@db:5432/golembrar?schema=publicvalue"
      - JWT_SECRET="variosnumerosletrasesimbolosmisturadosparasegurançadosecret"
      - JWT_EXP="1h"
    ports:
    - "3000:3000"

networks:
  default:
    driver: bridge
    name: golembrar

volumes:
  rabbitmq_data:
