
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE1ODkwMTg0LCJleHAiOjE3MTU4OTM3ODR9.z8T264ygfLuiDy4lxa-M6oCkOPovjI-uMzaJfxKzgBM

POST {{host}}/auth HTTP/1.1
Content-Type: application/json

{
    "email": "jhone.test14@gmail.com",
    "password": "senhaForte"
}

###

GET {{host}}/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
