#Rota para criaçãoo de contato com um usuario logado
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE1MjE0MDEzLCJleHAiOjE3MTUyMTc2MTN9.HA6rMVe5e4O8nwHOLaNF5a7UcN-EcbBRfHoktpwoxz8
###

POST {{host}}/contact HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "teste",
    "identify": "123456789",
    "platform": "whatsapp",
    "userId": 1
}

###

###Rota para pegar todos os contacts do usuario logado
GET {{host}}/contact HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### pegar um contact especifico de um usuario logado
GET {{host}}/contact/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

DELETE {{host}}/contact/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

PUT {{host}}/contact/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "name": "teste",
    "identify": "123456789",
    "platform": "whatsapp"
}
###
