#Rota para criaçãoo de contato com um usuario logado
@host = http://localhost:3000
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MmU5Y2M0ZS0zOGQ0LTRjNzUtOThiMi00NGUzZTJlM2Y0MmQiLCJpYXQiOjE3MjQyNTkxNjQsImV4cCI6MTcyNDI5MTU2NH0._sWzZdFO2IHyqMF8-U7IuJDCx0wrne8CFhNeAOkg_I8"
###

POST {{host}}/contact HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "teste",
    "identify": "user-contact@gmail.com",
    "platform": "email"
}

###

###Rota para pegar todos os contacts do usuario logado
GET {{host}}/contact HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### pegar um contact especifico de um usuario logado
GET {{host}}/contact/9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

DELETE {{host}}/contact/9 HTTP/1.1
Authorization: Bearer {{token}}

###

PATCH {{host}}/contact/10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "testeeeee",
    "identify": "123456713",
    "platform": "whatsapp"
}

###