### Create reminder

POST http://localhost:3000/reminder HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA3ODYzMjYwLCJleHAiOjE3MDc4NjY4NjB9.fF3EATw2HSYCV2W9EZqyaEMY2GVurj6xcxtJ1UH2s88

{
  "title" : "Lembrar de codar",
  "description" : "Lembrete para codar TypeScript pela manhã",
  "platform" : "Whatsapp",
  "scheduled" : "2024-02-23T01:06:18.179Z",
  "categoryId" : 1
}

### Get my user reminders

GET http://localhost:3000/reminder HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA3ODYzMjYwLCJleHAiOjE3MDc4NjY4NjB9.fF3EATw2HSYCV2W9EZqyaEMY2GVurj6xcxtJ1UH2s88

### Get reminder by id

GET http://localhost:3000/reminder/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA3ODYzMjYwLCJleHAiOjE3MDc4NjY4NjB9.fF3EATw2HSYCV2W9EZqyaEMY2GVurj6xcxtJ1UH2s88

### Update reminder

PATCH http://localhost:3000/reminder/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA3ODYzMjYwLCJleHAiOjE3MDc4NjY4NjB9.fF3EATw2HSYCV2W9EZqyaEMY2GVurj6xcxtJ1UH2s88

{
  "title" : "Lembrar de estudar",
  "description" : "Lembrete para estudar TypeScript pela manhã",
  "platform" : "Telegram",
  "scheduled" : "2024-02-22T01:06:18.179Z",
  "categoryId" : 1
}