### Create reminder

POST http://localhost:3000/reminder HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA3MDA3NDcxLCJleHAiOjE3MDcwMTEwNzF9.LuaFzejSz7PAlB-MEDMddHN9a06kFTbE2HQA5SfsqYk

{
  "title" : "Lembrar de codar",
  "description" : "Lembrete para codar TypeScript pela manhã",
  "platform" : "Whatsapp",
  "scheduled" : "2024-02-23T01:06:18.179Z",
  "categoryId" : 1
}

### Update reminder

PATCH http://localhost:3000/reminder/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA3MDA3NDcxLCJleHAiOjE3MDcwMTEwNzF9.LuaFzejSz7PAlB-MEDMddHN9a06kFTbE2HQA5SfsqYk

{
  "title" : "Lembrar de estudar",
  "description" : "Lembrete para estudar TypeScript pela manhã",
  "platform" : "Telegram",
  "scheduled" : "2024-02-22T01:06:18.179Z",
  "categoryId" : 1
}