@host = http://localhost:3000

### create one user account

POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "email" : "test1@email.com",
  "phone" : "19987851003",
  "password" : "senhaForte1"
}

### delete one user account

PATCH {{host}}/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEzODEzNjMyLCJleHAiOjE3MTM4MTcyMzJ9.1PiVvLtTjm5cTNKZ1-QEkKXqM4Bjx2Oc9tecADnEhaE

{
  "password": "senhaAtualizada"
}

###

DELETE http://localhost:3000/user/11

### get one user account

GET http://localhost:3000/user

### user login

POST http://localhost:3000/auth HTTP/1.1
Content-Type: application/json

{
  "email" : "test@email.com",
  "password" : "senhaForte"
}

### get all users account

GET http://localhost:3000/user