@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzE3MTg0MzI3LCJleHAiOjE3MTcxODc5Mjd9.b_wlaybmoGG0UMipmONbU2U_RGUDhe1-fmJGod7prJo

### create one user account

POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "email" : "victor.sena186@gmail.com",
  "phone" : "19987851001",
  "password" : "senhaForte123"
}

### delete one user account

DELETE http://localhost:3000/user
Authorization: Bearer {{token}}
Content-Type: application/json



### get one user account

GET http://localhost:3000/user/1

### user login

POST http://localhost:3000/auth HTTP/1.1
Content-Type: application/json

{
  "email" : "victor.sena186@gmail.com",
  "password" : "senhaForte123"
}

### get all users account

GET http://localhost:3000/user