### create one user account

POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "email" : "test@email.com",
  "phone" : "19987851001",
  "password" : "senhaForte"
}

### delete one user account

DELETE http://localhost:3000/user/11

### get one user account

GET http://localhost:3000/user/1

### user login

POST http://localhost:3000/auth HTTP/1.1
Content-Type: application/json

{
  "email" : "test@email.com",
  "password" : "senhaForte"
}

### get all users account

GET http://localhost:3000/user