### Create reminder
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjVmN2FlYS05ODQ0LTRmNmUtOGZkYS1mNGI3MWRjMzBkMzUiLCJpYXQiOjE3MjQyNjI5NDQsImV4cCI6MTcyNDI5NTM0NH0.W_6rbL9-fvQE7y9IIVzpMTdy-8pfPGsJsxQoi7gjosY

@host = http://localhost:3000

@reminderId = 1
# @name createReminder
POST {{host}}/reminder HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title" : "Lembrar de codar",
  "description" : "Lembrete para codar TypeScript pela manhã",
  "scheduled" : "2024-12-23T01:06:18.179Z",
  "usersToReminder" : ["f04...uuid-of-the-contact-here"]
}

### Get my user reminders


@reminderId = {{createReminder.response.body.reminder.id}}

###

GET {{host}}/reminder HTTP/1.1
Authorization: Bearer {{token}}

### Get reminder by id

GET {{host}}/reminder/{{reminderId}} HTTP/1.1
Authorization: Bearer {{token}}

### Update reminder

PATCH {{host}}/reminder/{{reminderId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title" : "Lembrar de estudar",
  "description" : "Lembrete para estudar TypeScript pela manhã",
  "scheduled" : "2024-02-22T01:06:18.179Z",
  "usersToReminder" : ["f04...uuid-of-the-contact-here-(if-need)"]
}

###

### Remove reminder

DELETE {{host}}/reminder/{{reminderId}} HTTP/1.1
Content-Type: application/application/json
Authorization: Bearer {{token}}

###