#o o token não atualiza os valores por aqui, somente o valor interno armazenado
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEzODEzNjMyLCJleHAiOjE3MTM4MTcyMzJ9.1PiVvLtTjm5cTNKZ1-QEkKXqM4Bjx2Oc9tecADnEhaE
@tokenRefresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzEzODEzNjMyLCJleHAiOjE3MTM4MTcyMzJ9.1PiVvLtTjm5cTNKZ1-QEkKXqM4Bjx2Oc9tecADnEhaE

### user login
# @name login
POST {{host}}/auth HTTP/1.1
Content-Type: application/json

{
  "email" : "usuario-qualquer@gmail.com",
  "password" : "senhaForte"
}

###

@token = {{login.response.body.token}}
@refreshToken = {{login.response.body.refreshToken}}

### create one user account

# @name createUser
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
  "email" : "usuario-qualquer@gmail.com",
  "name" : "Usuario Qualquer",
  "password" : "senhaForte"
}


### delete one user account
# @name updateUser
PATCH {{host}}/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "senhaAtualizada"
}

###

# @name deleteUser
DELETE {{host}}/user
Authorization: Bearer {{token}}
Content-Type: application/json



### get one user account
# @name getUser
GET {{host}}/user
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name refreshToken
GET {{host}}/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenRefresh}}

###

@tokenRefresh = {{refreshToken.response.body.refreshToken}}


###